cluster.name: Wreker
network.host: 0.0.0.0
plugin.mandatory: cloud-aws
cloud.aws.access_key: ${ACCESS_KEY}
cloud.aws.secret_key: ${SECRET_KEY}
discovery.type: ec2
discovery.zen.ping.multicast.enabled: false
discovery.ec2.groups: quantumSearch-v2
discovery.zen.minimum_master_nodes: 1
